language: python
python:
  - "3.5"
install: "pip3 install -r requirements.txt"
script: 
  - python3 manage.py makemigrations api
  - python3 manage.py migrate
  - python3 manage.py test
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cd modua
