# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-11 00:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_article_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdefinition',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_userdefinition_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userword',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_userword_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
