# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-29 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicword',
            old_name='transliteration',
            new_name='pinyin',
        ),
        migrations.RenameField(
            model_name='userword',
            old_name='transliteration',
            new_name='pinyin',
        ),
    ]
