# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='definition',
            old_name='translation',
            new_name='definition',
        ),
        migrations.RemoveField(
            model_name='word',
            name='article',
        ),
        migrations.AddField(
            model_name='word',
            name='article',
            field=models.ManyToManyField(null=True, to='api.Article'),
        ),
    ]
