# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-29 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170329_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicword',
            name='word',
            field=models.CharField(blank=True, max_length=512, unique=True),
        ),
    ]
