# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20160904_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='article',
            new_name='articles',
        ),
        migrations.RemoveField(
            model_name='word',
            name='users',
        ),
        migrations.AddField(
            model_name='word',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
