# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-29 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170329_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicdefinition',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='publicdefinition',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='userdefinition',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='userdefinition',
            name='modified_date',
        ),
        migrations.AlterField(
            model_name='publicword',
            name='pinyin',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='publicword',
            name='word',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='userword',
            name='ease',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userword',
            name='pinyin',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='userword',
            name='word',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterUniqueTogether(
            name='publicword',
            unique_together=set([('word', 'pinyin')]),
        ),
    ]
