# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-09 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170329_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='text',
            new_name='body',
        ),
    ]
