# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-09 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170409_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userword',
            name='ease',
            field=models.IntegerField(),
        ),
    ]
