# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-09 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170409_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userword',
            old_name='articles',
            new_name='article',
        ),
    ]
