# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-10 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160910_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userword',
            name='word',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterUniqueTogether(
            name='userword',
            unique_together=set([('owner', 'word')]),
        ),
    ]
