# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-10 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170409_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='userword',
            name='ease',
            field=models.IntegerField(default=0),
        ),
    ]
