# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-28 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170327_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='city',
            name='country_city',
        ),
        migrations.RemoveField(
            model_name='city',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='city',
            name='region_city',
        ),
        migrations.RemoveField(
            model_name='country',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='country',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='dictionaryapi',
            name='language',
        ),
        migrations.RemoveField(
            model_name='region',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='region',
            name='country',
        ),
        migrations.RemoveField(
            model_name='region',
            name='editor',
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='publicdefinition',
            name='definition',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='publicword',
            name='transliteration',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='publicword',
            name='word',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='userdefinition',
            name='definition',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='userword',
            name='transliteration',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='userword',
            name='word',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='DictionaryAPI',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
