# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 01:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import extras


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('pk_city_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=150, null=True)),
                ('added', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('pk_country_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=250, null=True)),
                ('added', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('fk_user_added_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_added_country', to=settings.AUTH_USER_MODEL)),
                ('fk_user_updated_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_updated_country', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Definitions',
            fields=[
                ('pk_definition_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('definition', models.CharField(max_length=8000, null=True)),
                ('transliteration', extras.CharNullField(blank=True, max_length=8000, null=True)),
                ('total_lookups', models.IntegerField(null=True)),
                ('user_added', models.IntegerField(null=True)),
                ('archived', models.BooleanField(default=False)),
                ('added', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('archived_date', models.DateTimeField(editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryApis',
            fields=[
                ('pk_dictionary_apis_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('api_name', models.CharField(max_length=150, null=True)),
                ('api_description', extras.CharNullField(blank=True, max_length=8000, null=True)),
                ('api_type', models.CharField(max_length=150, null=True)),
                ('api_site', models.CharField(max_length=2000, null=True)),
                ('api_base_url', models.CharField(max_length=2000, null=True)),
                ('api_key', models.CharField(max_length=500, null=True)),
                ('api_id_key', models.CharField(max_length=500, null=True)),
                ('added', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('fk_user_added_dic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_added_dic', to=settings.AUTH_USER_MODEL)),
                ('fk_user_updated_dic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_updated_dic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('pk_languages_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=150, null=True)),
                ('alphabet', models.CharField(max_length=300, null=True)),
                ('added', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('fk_user_added_lang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_added_lang', to=settings.AUTH_USER_MODEL)),
                ('fk_user_updated_lang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_updated_lang', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('pk_region_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=300, null=True)),
                ('added', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('fk_country_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_country_region', to='modua_app.Country')),
                ('fk_user_added_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_added_region', to=settings.AUTH_USER_MODEL)),
                ('fk_user_updated_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_updated_region', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDefinitions',
            fields=[
                ('pk_user_definitions_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('added', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('fk_definitions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_definitions', to='modua_app.Definitions')),
                ('fk_user_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WordTypes',
            fields=[
                ('pk_word_types_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('word_type', models.CharField(max_length=150, null=True)),
                ('added', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('fk_user_added_word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_added_word', to=settings.AUTH_USER_MODEL)),
                ('fk_user_updated_word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_updated_word', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='definitions',
            name='fk_definitionlang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_definitionlang', to='modua_app.Languages'),
        ),
        migrations.AddField(
            model_name='definitions',
            name='fk_dictionary_apis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_dictionary_apis', to='modua_app.DictionaryApis'),
        ),
        migrations.AddField(
            model_name='definitions',
            name='fk_sourcelang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_sourcelang', to='modua_app.Languages'),
        ),
        migrations.AddField(
            model_name='definitions',
            name='fk_user_contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_contributor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='definitions',
            name='fk_word_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_word_type_id', to='modua_app.WordTypes'),
        ),
        migrations.AddField(
            model_name='city',
            name='fk_country_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_country_city', to='modua_app.Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='fk_region_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_region_city', to='modua_app.Region'),
        ),
        migrations.AddField(
            model_name='city',
            name='fk_user_added_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_added_city', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='fk_user_updated_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_updated_city', to=settings.AUTH_USER_MODEL),
        ),
    ]
